config/routes.rb
Imageposter::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"} do
  end

  resources :image_posts do
    resources :posted_images
  end
  resources :posted_images
  resources :approvals, :only => [:create]
  root :to => 'image_posts#index'

end

app/models/image_post.rb
class ImagePost < ActiveRecord::Base
  include AASM
  aasm :column => :state do
    state :pending, :initial => true
    state :approved
    state :rejected

    event :approve, :after => :approve_images do
      transitions :to => :approved, :from => [:pending, :rejected]
    end
    event :reject, :after => :reject_images do
      transitions :to => :rejected, :from => [:pending, :approved]
    end
  end

  has_many :posted_images, :dependent => :destroy
  belongs_to :user

  accepts_nested_attributes_for :posted_images,
    :reject_if => lambda { |image| image['image'].nil? }

  validates_presence_of :title, :description

  attr_accessor :uuid_ref

  scope :approved, :conditions => { :state => 'approved' }
  scope :pending, :conditions => { :state => 'pending' }
  scope :for_user, lambda { |user|
    if( user.try(:admin?) )
      { :conditions => nil }
    elsif( user )
      { :conditions => [ "state = 'approved' or user_id = ?", user.id ] }
    else
      approved
    end
  }

  self.per_page = 10

  # this won't produce shorter than 8
  def simple_ellipsize(str, limit)
    if str.length <= 8
      return str
    elsif limit <= 8
      str[0..4] + "..."
    elsif str.length > limit
      str[0..limit-4] + "..."
    else
      str
    end
  end

  def ellipsized_title( limit = 40 )
    simple_ellipsize( title, limit )
  end

  def ellipsized_description( limit = 80 )
    simple_ellipsize( description, limit )
  end

  def owned_by?( user )
    !user.blank? && user.id == self.user_id
  end

  # note posted images' states are not utilised at the moment!
  def approve_images
    posted_images.each { |pi|
      pi.approve!
    }
  end

  # note posted images' states are not utilised at the moment!
  def reject_images
    posted_images.each { |pi|
      pi.reject!
    }
  end
end

app/models/posted_image.rb
require 'paperclip_processors/watermark'
class PostedImage < ActiveRecord::Base
  # note these are set but not utilised at the moment!
  include AASM
  aasm :column => :state do
    state :pending, :initial => true
    state :approved
    state :rejected

    event :approve do
      transitions :to => :approved, :from => [:pending, :rejected]
    end
    event :reject do
      transitions :to => :rejected, :from => [:pending, :approved]
    end
  end
  
  belongs_to :image_post
  belongs_to :user
  has_attached_file :image,
    :processors => [:watermark],
    :styles => {
      :thumb => "64x64",
      :large => {
        :geometry => '512x512',
        :watermark_path => "#{Rails.root}/public/images/watermark.png",
        :position => 'Center'
      }
    }
  validates_attachment_presence :image
  validates_attachment_size :image, :less_than => 5.megabytes
  validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png', 'image/bmp', 'image/gif', 'image/tiff']

  scope :approved, :conditions => { :state => 'approved' }
  scope :pending, :conditions => { :state => 'pending' }

  scope :owned_by, lambda { |user|
    { :conditions => [ "user_id = ?", user.id ] }
  }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :image_posts
  has_many :posted_images

  def admin?
    self.role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/approvals_controller.rb
class ApprovalsController < ApplicationController
  before_filter :authenticate_user!
  def create
    if current_user.admin?
      @image_post = ImagePost.find( params[:image_post_id] )
      if params[:type] == 'approve'
        if @image_post.approve!
          flash[:notice] = 'Post approved.'
        else
          flash[:alert] = 'Failed to approve post.'
        end
      elsif params[:type] == 'reject'
        if @image_post.reject!
          flash[:notice] = 'Post rejected.'
        else
          flash[:alert] = 'Failed to reject post.'
        end
      end
    else
      flash[:alert] = 'You must be admin to approve posts.'
    end
    redirect_to( image_posts_path )
  end
end

app/controllers/image_posts_controller.rb
class ImagePostsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  def index
    cond = nil
    if !current_user.blank? && params[:limit] == 'mine_only'
      cond = ['user_id = ?', current_user.id]
    end
    @image_posts = ImagePost.for_user(current_user).paginate(:page => params[:page], :conditions => cond )
  end
  def new
    @image_post = ImagePost.new
    @image_post.uuid_ref = UUIDTools::UUID.random_create.to_s
  end
  def show
    @image_post = ImagePost.for_user(current_user).find( params[:id] )
    @attached_images = @image_post.posted_images
  end
  def create
    @image_post = ImagePost.new( params[:image_post] )
    @image_post.user_id = current_user.id
    @image_post.posted_images = PostedImage.where( :temp_ref => @image_post.uuid_ref )
    @image_post.posted_images.each { |pi| pi.temp_ref = nil }
    if @image_post.save
      flash[:notice] = 'Your post has been saved successfully'
      redirect_to image_post_path( @image_post )
    else
      flash[:alert] = 'Sorry, could not save your post'
      render :action => 'new'
    end
  end
  def destroy
    @image_post = ImagePost.find(params[:id])
    if current_user.admin? || @image_post.owned_by?( current_user )
      if @image_post.destroy
        flash[:notice] = 'Post deleted successfully'
      end
    else
      flash[:alert] = 'You cannot delete that post'
    end
    redirect_to image_posts_path
  end
end

app/controllers/posted_images_controller.rb
class PostedImagesController < ApplicationController
  before_filter :authenticate_user!
  def show
    @posted_image = PostedImage.owned_by(current_user).find(params[:id])
    render :layout => false
  end

  def new
    # XXX: this is done by /image_post/<uuid>/posted_image/new.
    # So the :image_post_id is not really an existing image_post's id.
    # Is there a better way of doing this?
    @posted_image = PostedImage.new( :temp_ref => params[:image_post_id] )
    render :layout => false
  end

  def create
    # TODO: validate post image so that it either has image post or new ref set.
    @posted_image = PostedImage.new(params[:posted_image])
    @posted_image.user = current_user
    if @posted_image.save
      redirect_to( posted_image_path(@posted_image) )
    else
      render :action => 'new', :layout => false
    end
  end

  def update
    @posted_image = PostedImage.find(params[:id])
    # TODO: better results esp. for error
    if @posted_image.update_attributes( params[:posted_image] )
      render :text => 'OK' if request.xhr?
    else
      render :text => 'FAIL' if request.xhr?
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def create
    super
    if( User.count == 1 )
      @only_user = User.last
      @only_user.role = 'admin'
      @only_user.save!
      flash[:notice] += ' As you are the first user, you are now an admin.'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/approvals_helper.rb
module ApprovalsHelper
end

app/helpers/image_posts_helper.rb
module ImagePostsHelper
  def approve_link( post )
    button_to 'Approve', approvals_path( :image_post_id => post, :type => 'approve' ), :method => 'post'
  end

  def reject_link( post )
    button_to 'Reject', approvals_path( :image_post_id => post, :type => 'reject' ), :method => 'post'
  end

  def approval_links( post )
    case( post.state )
    when 'approved'
      rval = reject_link( post )
    when 'rejected'
      rval = approve_link( post )
    when 'pending'
      rval = approve_link( post ) + ' ' + reject_link( post ) 
    end
  end

  def switch_mine_only_link
    if( params[:limit] == 'mine_only' )
      link_to "List everyone's posts", image_posts_path
    else
      link_to 'Only list my own posts', image_posts_path( :limit => :mine_only )
    end
  end
end

app/helpers/posted_images_helper.rb
module PostedImagesHelper
end

app/views/image_posts/index.html.haml
%h2
  List of Image Posts
  = " (page #{params[:page]})" unless params[:page].blank?

= link_to 'Create New Post', new_image_post_path
= switch_mine_only_link unless current_user.blank?
%br

- if @image_posts.empty?
  %p
    No record found
- else
  = will_paginate @image_posts
  %table
    %tr.header_row
      %th Id
      %th Thumbnail(s)
      %th Title
      %th Description
      %th State
      %th Action
    - @image_posts.each do |image_post|
      %tr.content_row{ :class => cycle( 'odd', 'even' ) }
        %td
          = image_post.id
        %td
          - image_post.posted_images[0..3].each do |pi|
            = link_to image_tag( pi.image.url(:thumb) ), image_post_path(image_post)
        %td
          = link_to image_post.ellipsized_title, image_post_path(image_post)
        %td
          = link_to image_post.ellipsized_description, image_post_path(image_post)
        %td
          = image_post.state
          - if !current_user.blank? && !image_post.owned_by?(current_user)
            %br
            = ' (not mine)'
        %td
          - if current_user.try(:admin?)
            = raw approval_links( image_post )
          - if current_user.try(:admin?) || image_post.owned_by?( current_user )
            = button_to 'Delete', image_post_path(image_post), :method => :delete, :confirm => 'Are you sure?', :title => 'Delete Post'
  = will_paginate @image_posts

app/views/image_posts/new.html.haml
= link_to 'Back to Index', image_posts_path
%h2 Create new post
= form_for @image_post, :html => { :multipart => true } do |f|
  = f.hidden_field :uuid_ref
  = f.label 'Post Title:', :for => :title
  %br
  = f.text_field :title
  %br
  = f.label 'Description:', :for => :title
  %br
  = f.text_area :description
  %br
  %h3 Image(s):

  - PostedImage.where( :temp_ref => @image_post.uuid_ref ).each do |pi|
    %iframe.image_upload_frame{ :src => posted_image_path( pi ) }

  %iframe.image_upload_frame{ :src => new_image_post_posted_image_path( :image_post_id => @image_post.uuid_ref) }
  = f.submit 'submit'

%br
= link_to 'Back to Index', image_posts_path

app/views/image_posts/show.html.haml
= link_to 'Back to Index', image_posts_path
- if current_user.try(:admin?)
  %br
  %h3
    State:
    = @image_post.state
  =raw approval_links( @image_post )
%h2
  Title:
  = @image_post.title
%h3
  Description:
  = @image_post.description
- @attached_images.each do |posted_image|
  %div.posted_image
    Name:
    = posted_image.name
    %br
    Description:
    = posted_image.description
    %br
    = link_to image_tag( posted_image.image.url(:large) ), posted_image.image.url(:original)

%br
= link_to 'Back to Index', image_posts_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Imageposter</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="login_info" >
    <% if current_user %>
      Logged in as: <%= current_user.email %>
      <%= link_to '(Logout)', destroy_user_session_path, :method => :delete %>
    <% else %>
      You are not logged in.
      <%= link_to '(Login)', new_user_session_path %>
      <%= link_to '(Register)', new_user_registration_path %>
    <% end %>
  </div>

  <h1 class="site_name">Image Poster Application</h1>
  <div class="headergap"> </div>

  <% unless flash[:notice].blank? %>
    <p class="notice"><%= flash[:notice] %></p>
  <% end %>
  <% unless flash[:alert].blank? %>
    <p class="alert"><%= flash[:alert] %></p>
  <% end %>

<%= yield %>

</body>
</html>

app/views/posted_images/_form.html.haml
- if !@posted_image.try(:errors).blank?
  = @posted_image.errors.full_messages.join(', ')
= javascript_include_tag "application"
= form_for form, :html => { :multipart => true } do |f|
  = f.hidden_field :temp_ref
  = f.label 'Name:', :for => 'name'
  = f.text_field :name
  = f.label 'Description:', :for => 'description'
  = f.text_field :description
  %br
  = f.label 'File:', :for => 'image'
  = f.file_field :image, :class => 'image_upload_file_field'
  %br

app/views/posted_images/new.html.haml
= stylesheet_link_tag "application"
= render :partial => 'form', :object => @posted_image

app/views/posted_images/show.html.haml
= javascript_include_tag "application"
= stylesheet_link_tag "application"

= form_for @posted_image, :html => { :class => 'inlineform' } do |f|
  = f.label 'Name:', :for => :name
  = f.text_field :name, :onkeypress => "return event.keyCode!=13;", :onchange => "update_name( '#{posted_image_url}', $(this), #{@posted_image.id} );"
  = image_tag '/images/spinner_small.gif', :style => 'display: none', :id => "posted_image_#{@posted_image.id}_name_spinner"

= form_for @posted_image, :html => { :class => 'inlineform' } do |f|
  = f.label 'description:', :for => :description
  = f.text_field :description, :onkeypress => "return event.keyCode!=13;", :onchange => "update_desc( '#{posted_image_url}', $(this), #{@posted_image.id} );"
  = image_tag '/images/spinner_small.gif', :style => 'display: none', :id => "posted_image_#{@posted_image.id}_desc_spinner"

%br
= image_tag( @posted_image.image.url(:thumb) )